--SET ADMIN ROLE
USE ROLE SYSADMIN;

--CREATE VIRTUAL WAREHOUSE WITH THE NAME COMPUTE_WH
CREATE WAREHOUSE COMPUTE_WH WITH
WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;
